<?php

/**
 * @file minisite.module
 * Module file.
 */

define('MINISITE_UPLOADPATH', 'minisite/upload');
define('MINISITE_ASSETPATH', 'minisite/static');
define('MINISITE_EXTENSIONS', 'html htm js css png jpg gif pdf doc docx ppt pptx xls xlsx tif xml txt');
define('MINISITE_MAXFILESIZE', file_upload_max_size());
define('MINISITE_HASHSALT', 'minisite');

// Load all Field module hooks for Minisite.
require_once dirname(__FILE__) . '/includes/minisite.field.inc';
// Load all theme hooks for Minisite.
require_once dirname(__FILE__) . '/includes/minisite.theme.inc';

/**
 * Implements hook_help().
 */
function minisite_help($path, $arg) {
  switch ($path) {
    case 'admin/help#minisite':
      $output = '<p>' . t("Provides the ability to upload arbitrary 'minisites' to a Drupal website.") . '</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function minisite_permission() {
  return array(
    'administer minisite' => array(
      'title' => t('Administer Minisite'),
      'description' => t('Allows users to administer minisite settings.'),
    ),
  );
}
